site_name: pyERGM
site_url: https://tomtalp.github.io/pyERGM/
theme:
  name: material
  palette:
    scheme: default
    primary: blue

nav:
  - Home: index.md
  - Overview: overview.md
  - Fitting a model: fitting.md
  - Evaluating model performance: evaluating.md
  - Metrics:
    - Introduction to graph metrics: metrics.md
    - Creating custom metrics: custom_metrics.md
  - API Reference:
    - ERGM: api/ergm.md
    - Metrics: api/metrics.md
    - Sampling: api/sampling.md
    - Datasets: api/datasets.md
    - Utils: api/utils.md
    

markdown_extensions:
  - pymdownx.superfences 
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

repo_name: 'pyERGM'
repo_url: 'https://github.com/tomtalp/pyERGM'

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_root_toc_entry: false
            members_order: source
            filters:
              - "!^_"
            merge_init_into_class: true
            separate_signature: true
